version: 2
jobs:
  build:
    working_directory: /go/src/github.mheducation.com/goplaygound/goci
    docker:
       # note: this docker image already has gometalinter + glide, so we do not need
       - image: azuka/ci-golang:1.9
    environment:
      - GOPATH: /go
      - CIRCLE_TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Run Circle Linter
          command: |
            make lint-circle || make lint
      - run:
          name: Run Circle Tests
          command: |
            make test-circle
            make coverage
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results

workflows:
  version: 2
  test-matrix:
    jobs:
      - build
